development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Meixiaoshi
  admin_email: beenhero@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.meixiaoshi.com
  site_name: Meixiaoshi
  admin_email: beenhero@gmail.com
  
production:
  site_url: http://www.meixiaoshi.com
  site_name: Meixiaoshi
  admin_email: beenhero@gmail.com
